config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get '/authors', to: "lists#get_authors"
  # resources :lists, only: [:index, :new, :show, :create]
  resources :poems, :authors, :lists
    # get 'show', to: 'poems#show'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# class Author < ApplicationRecord
#   has_many :lists
#   has_many :poems, through: :lists 
#   validates :name, presence: true
# end

# class Author < ApplicationRecord
#   has_many :lists
#   has_many :poems, through: :lists 
#   validates :name, presence: true
# end

class Author < ApplicationRecord
  has_many :poems
  has_many :lists, through: :poems 
  validates :name, presence: true
end

app/models/list.rb
# class List < ApplicationRecord
#   belongs_to :author
#   belongs_to :poem
#   validates :owner_name, presence: true
#   # accepts_nested_attributes_for :poems

#   # def poems_attributes=(poems_attributes)
#   #   # raise poems_attributes.inspect
#   #   poems_attributes.values.each do |poem_attributes|
#   #     self.poems.build(poem_attributes)
#   #   end
#   # end
# end

class List < ApplicationRecord
  # has_many :authors
  # has_many :authors, through: :poems
  # validates :owner_name, presence: true

  # belongs_to :poems
  # belongs_to :authors
  # validates :owner_name, presence: true, uniqueness: true
  # validates :author_name, uniqueness: true
  # accepts_nested_attributes_for :poems

  
    has_many :poems
    has_many :authors, through: :poems
    validates :owner_name, presence: true, uniqueness: true
    # validates :owner_name, presence: true


  def poems_attributes=(poems_attributes)
    # raise poems_attributes.inspect
    poems_attributes.values.each do |poem_attributes|
      self.poems.build(poem_attributes)
    end
  end
  
end

app/models/poem.rb
# class Poem < ApplicationRecord
#   has_many :lists
#   has_many :authors, through: :lists
#   validates :author_name, presence: true
#   # accepts_nested_attributes_for :lists

#   def lists_attributes=(lists_attributes)
#     # raise poems_attributes.inspect
#     lists_attributes.values.each do |list_attributes|
#       self.lists.build(list_attributes)
#     end
#   end  
# end

# class Poem < ApplicationRecord
#   has_many :lists
#   has_many :authors, through: :lists
  
#   validates :author_name, presence: true
  
#   # accepts_nested_attributes_for :lists  
# end

class Poem < ApplicationRecord
  belongs_to :author
  belongs_to :list, optional: true
  
  validates :author_name, presence: true
  
  # accepts_nested_attributes_for :lists  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  # def index
  #   render({json: Author.all})
  # end

  def index
    @authors = Author.all 
    # binding.pry
  end

  def new
    @author = Author.new 
  end


  def create  
    @author = Author.new(author_params)
    # byebug
    if @author.save
      redirect_to @author
    else
      render :new
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  private
    def author_params
      params.require(:author).permit(:name)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   
  def index
    @lists = List.all 
  end

  # def index
  #   render({json: List.all})
  # end

  def show
    @list = List.find(params[:id])
  end
    
  def new
    @list = List.new  
    # @list.poems.build(:author_name => "name", :title => "title", :lines => "lines")
    # @list.build_poems(:author_name => "name", :title => "title", :lines => "lines")
    # @list.poems.build(author_name: 'name', title: 'title', lines: 'lines')
  end

  def create
    # raise params.inspect
    # @list = List.create(list_params)
    # redirect_to @list

    @list = List.new(list_params)
    
    if @list.save
      redirect_to @list
    else
      # binding.pry
      render :new
    end
  end
    
  private

  def list_params
    params.require(:list).permit(:owner_name, poem_ids: [] )
    # params.require(:list).permit(:owner_name, :poems_attributes => [:lines])
    # params.require(:list).permit(:author_name, :title, poems_attributes: [:author_name, :title, :lines])
  end
    
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  
  # def index
  #   render({json: Poem.all})
  #   binding.pry
  # end

  def index
    @poems = Poem.all 
    # binding.pry
  end

  def new
    @poem = Poem.new 
    # @poem.lists.build(:owner_name => "name")

  end

  def create  
    @poem = Poem.new(poem_params)
    # byebug
    if @poem.save
      redirect_to @poem
    else
      render :new
    end
  end

  def show
    @poem = Poem.find(params[:id])
  end
  

  private
    def poem_params
      # params.require(:poem).permit(:author_name, :title, :lines)
      # params.require(:poem).permit(:title)
      params.require(:poem).permit(:author_name, :title_name, :lines)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/my_lists_helper.rb
module MyListsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
    
    <li><%= link_to author.name, author_path(author) %></li><br>
   
    <% end %>
</ul>

app/views/authors/new.html.erb
<h2>Request Poem Lines</h2>

<%= form_for @author do |f| %>
  
  <p>
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </p>

  <%= f.submit %>
<% end %>
 
</form>
    

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

  <ul>
  <% @author.poems.each do |poem| %>
    <h2><%= link_to poem.title_name, poem_path(poem) %></h2>
    <% end %>
  </ul>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoetryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",  "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists of People's Favorite Poems and Lines</h1>

<ul>
  <% @lists.each do |list| %>
    
    <li><%= link_to list.owner_name, list_path(list) %></li><br>
   
    <% end %>
</ul>

<%= link_to "Create new list", new_list_path  %><br><br>

app/views/lists/new.html.erb
<h2>Create list of favorite lines from Poems</h2>

<% if @list.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@list.errors.count, "error") %>
      prohibited this list from being saved:
    </h2>

    <ul>
    <% @list.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@list) do |f| %>

  <p>
  <%= f.label :owner_name %>
  <%= f.text_field :owner_name %>
  </p>

  <p>
  <%= f.label :lines %>:<br>
  <%= f.collection_check_boxes(:poem_ids, Poem.all, :id, :lines, prompt: true) do |b| %>
  <p><%= b.label(:"data-value" => b.value) { b.check_box + b.text } %></p>
  <% end %>
  </p>


  <%= f.submit %>
  
<% end %>

app/views/lists/show.html.erb
<h2><%= " #{@list.owner_name} Poem List" %></h2>

<p>
  
  <% @list.poems.each do |p| %>
  <h3>Author:</h3>
  <%= p.author_name %>
  <h3>Title:</h3>
  <%= p.title_name %>
  <h3>Lines:</h3>
  <%= p.lines %>   
  <% end %>
</p>

<%= link_to 'Back', lists_path %>


  

app/views/poems/index.html.erb
<h1>Poems</h1>

<ul>
  <% @poems.each do |poem| %>
 
    <li><%= link_to poem.author_name, poem_path(poem) %></li><br>
    <% end %>
</ul>


  

app/views/poems/new.html.erb
<h2>Poems</h2>

<%= form_for @poem do |f| %>
  

  <p>
    <%= f.label :author_name %>
    <%= f.collection_select :author_name, Poem.all, :author_name, :author_name, prompt: true %>
  </p>

  <p>
    <%= f.label :title %>
    <%= f.collection_select :title, Poem.all, :title, :title, prompt: true %>
  </p>
    
  <%= f.submit %>
    
  <% end %>

</form>
    

app/views/poems/show.html.erb
<h2>Poem Details </h2>

<p>
  <h3>Name:</h3>
  <h2><%= link_to @poem.author_name, author_path(@poem)  %></h2>
  <h3>Title:</h3>
  <h2><%= link_to @poem.title, author_path(@poem) %></h2>
  <h3>Lines:</h3>
  <h2><%= @poem.lines %></h2>
</p>